language: r
warnings_are_errors: false
sudo: required
dist: trusty
after_success: travis_wait 20 after_success

addons:
    apt:
        packages:
            - libgdal-dev
            - libproj-dev
            - libnetcdf-dev
            - netcdf-bin

r_packages:
    - devtools
    - rgdal
    - rgeos
    - ncdf4
    - covr
env:
    global:
        - _R_CHECK_FORCE_SUGGESTS_=False
        - _R_CHECK_CRAN_INCOMING=False

after_success:
        - Rscript -e 'library(covr); codecov(type="all")'

